config/routes.rb
Rails.application.routes.draw do
  get 'reconciliations/page1' => "reconciliations#page1", as: 'page1'
  get 'reconciliations/page2' => "reconciliations#page2", as: 'page2'
  get 'reconciliations/page3' => "reconciliations#page3", as: 'page3'
  get 'reconciliations/page4' => "reconciliations#page4", as: 'page4'
  get 'reconciliations/page5' => "reconciliations#page5", as: 'page5'
  get 'reconciliations/page6' => "reconciliations#page6", as: 'page6'
  get 'reconciliations/page7' => "reconciliations#page7", as: 'page7'
  get 'reconciliations/page8' => "reconciliations#page8", as: 'page8'
  get 'reconciliations/page9' => "reconciliations#page9", as: 'page9'
  get 'reconciliations/page10' => "reconciliations#page10", as: 'page10'
  get 'reconciliations/page11' => "reconciliations#page11", as: 'page11'
  get 'reconciliations/page12' => "reconciliations#page12", as: 'page12'
  get 'reconciliations/page13' => "reconciliations#page13", as: 'page13'
  get 'reconciliations/page14' => "reconciliations#page14", as: 'page14'

  get 'users/:id/exit' => 'users#exit', as: 'user_exit'
  get 'users/:id/withdrawal' => 'users#withdrawal', as: 'withdrawal'

  resources :sharings, only: [:new, :create, :show, :edit, :update, :destroy]
  resources :meetings
  resources :notifications, only: [:index, :destroy]

  resources :messages, only: [:create]
  resources :rooms, only: [:create, :show]

  resources :posts do
    resource :favorites, only: [:create, :destroy]
    resources :post_comments, only: [:create, :destroy]
  end

  resources :tags do
    get 'posts', to: 'posts#search'
  end

  root to: 'homes#top'
  devise_for :users

  resources :users, only: [:show, :edit, :update] do
    resource :relationships, only: [:create, :destroy]
    get 'followings' => 'relationships#followings', as: 'followings'
    get 'followers' => 'relationships#followers', as: 'followers'
  end
  get 'homes/about'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/meeting.rb
class Meeting < ApplicationRecord

  belongs_to :user

  def self.search(search) # self.でクラスメソッドとしている
    if search # Controllerから渡されたパラメータが!= nilの場合は、titleカラムを部分一致検索
      Meeting.where(['name LIKE ?', "%#{search}%"])
    else
      Meeting.all # 全て表示。
    end
  end
end

app/controllers/meetings_controller.rb
class MeetingsController < ApplicationController
  before_action :set_meeting, only: %i(show edit update destroy)

  # GET /meetings or /meetings.json
  def index
    @meetings = Meeting.where(user_id: current_user)
  end

  # GET /meetings/1 or /meetings/1.json
  def show
  end

  # GET /meetings/new
  def new
    @meeting = Meeting.new
  end

  # GET /meetings/1/edit
  def edit
  end

  # POST /meetings or /meetings.json
  def create
    @meeting = Meeting.new(meeting_params)
    @meeting.user_id = current_user.id
    respond_to do |format|
      if @meeting.save
        format.html { redirect_to @meeting, notice: "記念日を登録しました。" }
        format.json { render :show, status: :created, location: @meeting }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @meeting.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /meetings/1 or /meetings/1.json
  def update
    respond_to do |format|
      if @meeting.update(meeting_params)
        format.html { redirect_to @meeting, notice: "記念日を更新しました。" }
        format.json { render :show, status: :ok, location: @meeting }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @meeting.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /meetings/1 or /meetings/1.json
  def destroy
    @meeting = Meeting.find(params[:id])
    @meeting.destroy
    respond_to do |format|
      format.html { redirect_to meetings_url, notice: "記念日を削除しました。" }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_meeting
    @meeting = Meeting.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def meeting_params
    params.require(:meeting).permit(:name, :start_time)
  end
end

app/helpers/meetings_helper.rb
module MeetingsHelper
end

app/views/meetings/_form.html.erb
<%= form_with(model: meeting, local: true) do |form| %>
  <% if meeting.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(meeting.errors.count, "error") %> prohibited this meeting from being saved:</h2>

      <ul>
      <% meeting.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <p class="label"><%= form.label :記念日 %></p>
    <%= form.text_field :name, class: "inputs" %>
  </div>

  <div class="field">
    <p class="label"><%= form.label :日付 %></p>
    <div class="date"><%= form.datetime_select :start_time %></div>
  </div>

  <div class="actions mt-5">
    <%= form.submit %>
  </div>
<% end %>

app/views/meetings/edit.html.erb
<p class="lead-form mt-5">記念日の編集</p>

<%= render 'form', meeting: @meeting %>

app/views/meetings/index.html.erb
<div class="calender mt-5">
  <%= month_calendar events: @meetings do |date, meetings| %>
    <%= date %>

    <% meetings.each do |meeting| %>
      <div>
        <%= link_to meeting_path(meeting) do %>
          <p class="text-danger h6"><%= meeting.name%></p>
        <% end %>
      </div>
    <% end %>
  <% end %>
</div>


<%= link_to '記念日を登録する', new_meeting_path, class: "btn btn-sm btn-outline-secondary mt-4 mb-5" %>

<h2 class="mb-4">記念日一覧</h2>

<table class="table table-sm table-striped">
  <thead>
    <tr>
      <th scope="col">何の記念日？</th>
      <th scope="col">日付</th>
    </tr>
  </thead>
  <tbody>
    <% @meetings.each do |meeting| %>
      <tr>
        <td>
          <%= link_to meeting_path(meeting) do %>
            <%= meeting.name %>
          <% end %>
        </td>
        <td><%= meeting.start_time.strftime('%Y/%m/%d') %></td>
        <td><%= link_to "削除する",meeting_path(meeting.id), method: :delete, class: "text-danger" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/meetings/new.html.erb
<p class="lead-form mt-5">記念日の記録</p>

<%= render 'form', meeting: @meeting %>

app/views/meetings/show.html.erb
<div class="show text-center mt-5">
  <p>
    <strong>記念日:</strong>
    <%= @meeting.name %>
  </p>

  <p class="mt-4 mb-4">
    <strong>日付:</strong>
    <%= @meeting.start_time.strftime('%Y/%m/%d') %>
  </p>

  <%= link_to '編集する', edit_meeting_path(@meeting), class: "btn btn-success text-white px-3 mr-4" %>
  <%= link_to '戻る', meetings_path, class: "btn btn-primary text-white px-4"  %>
</div>