config/routes.rb
Rails.application.routes.draw do
  get 'reconciliations/page1' => "reconciliations#page1", as: 'page1'
  get 'reconciliations/page2' => "reconciliations#page2", as: 'page2'
  get 'reconciliations/page3' => "reconciliations#page3", as: 'page3'
  get 'reconciliations/page4' => "reconciliations#page4", as: 'page4'
  get 'reconciliations/page5' => "reconciliations#page5", as: 'page5'
  get 'reconciliations/page6' => "reconciliations#page6", as: 'page6'
  get 'reconciliations/page7' => "reconciliations#page7", as: 'page7'
  get 'reconciliations/page8' => "reconciliations#page8", as: 'page8'
  get 'reconciliations/page9' => "reconciliations#page9", as: 'page9'
  get 'reconciliations/page10' => "reconciliations#page10", as: 'page10'
  get 'reconciliations/page11' => "reconciliations#page11", as: 'page11'
  get 'reconciliations/page12' => "reconciliations#page12", as: 'page12'
  get 'reconciliations/page13' => "reconciliations#page13", as: 'page13'
  get 'reconciliations/page14' => "reconciliations#page14", as: 'page14'

  get 'users/:id/exit' => 'users#exit', as: 'user_exit'
  get 'users/:id/withdrawal' => 'users#withdrawal', as: 'withdrawal'

  resources :sharings, only: [:new, :create, :show, :edit, :update, :destroy]
  resources :meetings
  resources :notifications, only: [:index, :destroy]

  resources :messages, only: [:create]
  resources :rooms, only: [:create, :show]

  resources :posts do
    resource :favorites, only: [:create, :destroy]
    resources :post_comments, only: [:create, :destroy]
  end

  resources :tags do
    get 'posts', to: 'posts#search'
  end

  root to: 'homes#top'
  devise_for :users

  resources :users, only: [:show, :edit, :update] do
    resource :relationships, only: [:create, :destroy]
    get 'followings' => 'relationships#followings', as: 'followings'
    get 'followers' => 'relationships#followers', as: 'followers'
  end
  get 'homes/about'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable


  validates :login_name, uniqueness: true
  validates :email, uniqueness: true


  has_many :posts, dependent: :destroy
  has_many :post_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :sharings, dependent: :destroy
  attachment :profile_image

  has_many :reverse_of_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  has_many :followers, through: :reverse_of_relationships, source: :follower

  has_many :relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  has_many :followings, through: :relationships, source: :followed

  has_many :active_notifications, class_name: 'Notification', foreign_key: 'visitor_id', dependent: :destroy
  has_many :passive_notifications, class_name: 'Notification', foreign_key: 'visited_id', dependent: :destroy

  has_many :messages, dependent: :destroy
  has_many :entries, dependent: :destroy

  has_many :meetings, dependent: :destroy

  def active_for_authentication
    super && (is_valid == false)
  end

  def follow(user_id)
    relationships.create(followed_id: user_id)
  end

  def unfollow(user_id)
    relationships.find_by(followed_id: user_id).destroy
  end

  def following?(user)
    followings.include?(user)
  end

  def create_notification_follow!(current_user)
    temp = Notification.where(["visitor_id = ? and visited_id = ? and action = ? ", current_user.id, id, 'follow'])
    if temp.blank?
      notification = current_user.active_notifications.new(
        visited_id: id,
        action: 'follow'
      )
      notification.save if notification.valid?
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, only: [:show]

  def show
    @user = User.find(params[:id])
    @sharing = Sharing.find_by(user_id: @user.id)
    @posts = @user.posts.page(params[:page]).reverse_order
    @currentUserEntry = Entry.where(user_id: current_user.id)
    @userEntry = Entry.where(user_id: @user.id)
    unless @user.id == current_user.id
      @currentUserEntry.each do |cu|
        @userEntry.each do |u|
          if cu.room_id == u.room_id
            @isRoom = true
            @roomId = cu.room_id
          end
        end
      end
      if @isRoom
      else
        @room = Room.new
        @entry = Entry.new
      end
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    @user.update(user_params)
    redirect_to user_path(@user)
  end

  def exit
  end

  def withdrawal
    @user = User.find(params[:id])
    @user.update(is_valid: true)
    reset_session
    flash[:notice] = "退会処理を実行いたしました"
    redirect_to root_path
  end

  private

  def user_params
    params.require(:user).permit(:name, :nickname, :email, :favorite_food, :hobby, :login_name, :profile_image)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
<p class="lead-form mt-5">編集画面<p2>
<%= form_with model: @user, local: true do |f| %>
  <div class= "field">
    <%= f.label :名前,class: "label" %><br />
    <%= f.text_field :name, autofocus: true, class: "inputs" %>
  </div>

  <div class= "field">
    <%= f.label :ニックネーム,class: "label" %><br />
    <%= f.text_field :nickname, class: "inputs" %>
  </div>

  <div class="field">
    <%= f.label :メールアドレス,class: "label" %><br />
    <%= f.email_field :email, autofocus: true, autocomplete: "email", class: "inputs" %>
  </div>

  <div class ="field">
    <%= f.label :好きな食べ物,class: "label" %><br />
    <%= f.text_field :favorite_food, class: "inputs" %>
  </div>

  <div class ="field">
    <%= f.label :趣味,class: "label" %><br />
    <%= f.text_field :hobby, class: "inputs" %>
  </div>

  <div class ="field">
    <%= f.label :共通のログインコード,class: "label text-nowrap" %><br />
    <%= f.text_field :login_name, class: "inputs" %>
  </div>

  <div class="field">
    <%= f.label :プロフィール画像,class: "label text-nowrap" %><br />
    <%= f.attachment_field :profile_image, placeholder: "プロフィール画像", class: "inputs" %>
  </div>

  <%= f.submit "保存する", class: "btn btn-success mt-3 px-5" %>
<% end %>

app/views/users/exit.html.erb
<main>
  <div class="text-center pt-5">
    <h2>本当に退会しますか？</h2>
    <p>退会すると、会員登録情報や</br>
       これまで投稿の閲覧ができなくなります。</br>
       退会する場合は、「退会する」をクリックしてください。
    </p>
    <%= link_to "退会しない", user_path(current_user),class: "btn btn-primary mr-5 px-5 text-white" %>
    <%= link_to "退会する", withdrawal_path(current_user),class: "btn btn-danger px-5 text-white"%>
  </div>
</main>

app/views/users/show.html.erb
 <div class="row">
   <div class="col-12 col-xl-5 ml-5 mr-5 pl-5 mb-5">
      <div class="profile_box">
        <div class="box-title">プロフィール</div>
        <div class="profile_center">
          <%= attachment_image_tag @user, :profile_image, :fill, 100, 100, format: 'jpeg', fallback: "no_image.jpg", class: "profile_figure" %>
          <div class="profile_name"><%= @user.name %></div>
        </div>
          <p>ニックネーム:<%= @user.nickname %></p>
        <ul>
          <li><i class="fas fa-angle-double-right icon mr-1"></i>好きな食べ物：<%= @user.favorite_food %></li>
          <li><i class="fas fa-angle-double-right icon mr-1"></i>趣味：<%= @user.hobby %></li>
          <li><i class="fas fa-angle-double-right icon mr-1"></i>フォロー：<%= link_to @user.followings.count, user_followings_path(@user.id), class: "text-primary" %> フォロワー：<%= link_to @user.followers.count, user_followers_path(@user.id), class: "text-primary" %></li>
          <li>
            <% if @user == current_user %>
              <%= link_to "編集する", edit_user_path(current_user),class: "btn btn-success text-white" %> <%= link_to "退会する", user_exit_path(current_user.id), class: "btn btn-danger text-white" %>
            <% end %>
          </li>
          <li>
            <% if @user.id != current_user.id %>
              <% if current_user.following?(@user) %>
                <%= link_to "フォローを外す", user_relationships_path(@user.id), method: :delete, class: "btn btn-danger text-white" %>
              <% else %>
                <%= link_to "フォローする", user_relationships_path(@user.id), method: :post, class: "btn btn-primary text-white" %></td>
              <% end %>
            <% end %>
          </li>
          <li>
            <% if @user.id != current_user.id %>
              <% if (current_user.following? @user) && (@user.following? current_user)  %>
                <% if @isRoom == true %>
                  <p class="user-show-room"><a href="/rooms/<%= @roomId %>" class="btn btn-primary btn-lg text-white">チャットへ</a>
                <% else %>
                  <%= form_for @room do |f| %>
                    <%= fields_for @entry do |e| %>
                      <%= e.hidden_field :user_id, value: @user.id %>
                    <% end %>
                      <%= f.submit "チャットを始める", class: "btn btn-primary btn-lg user-show-chat"%>
                  <% end %>
                <% end %>
              <% end %>
            <% end %>
          </li>
        </ul>
      </div>
   </div>
   <div class="col-12 col-xl-5 ml-5">
    <% if @sharing %>
      <div class="profile_box2">
          <div class="box-title2">プロフィール</div>
        <div class="profile_center2">
          <%= attachment_image_tag @sharing, :profile_image, :fill, 100, 100, format: 'jpeg', fallback: "no_image.jpg", class: "profile_figure2" %>
          <div class="profile_name2"><%= @sharing.name %></div>
        </div>
        <p>ニックネーム:<%= @sharing.nickname %></p>
        <ul>
            <li><i class="fas fa-angle-double-right icon2 mr-1"></i>好きな食べ物：<%= @sharing.favorite_food %></li>
            <li><i class="fas fa-angle-double-right icon2 mr-1"></i>趣味：<%= @sharing.hobby %></li>
            <li><i class="fas fa-angle-double-right icon2 mr-1"></i>関係：<%= @sharing.type %></li>
          <% if @user == current_user %>
            <li><%= link_to "編集する", edit_sharing_path(@sharing),class: "btn btn-success text-white" %>　<%= link_to "削除する", sharing_path(@sharing.id), method: :delete, class: "btn btn-danger text-white" %></li>
          <% end %>
        </ul>
      </div>
    <% else %>
      <% if @user == current_user %>
        <%= link_to "共有する人を登録する", new_sharing_path, class: "btn btn-primary m-5 text-white" %>
      <% end %>
    <% end %>
   </div>
 </div>

<div class="wrapper grid text-center">
  <% @posts.each do |post| %>
    <div class="item">
      <%= link_to post_path(post.id) do %>
        <%= attachment_image_tag post,:image,width: "200", height: "200", class: "img"%>
      <% end %>
      <p><%= post.created_at.strftime('%Y/%m/%d') %></p>
    </div>
  <% end %>
</div>