config/routes.rb
Rails.application.routes.draw do
  get 'reconciliations/page1' => "reconciliations#page1", as: 'page1'
  get 'reconciliations/page2' => "reconciliations#page2", as: 'page2'
  get 'reconciliations/page3' => "reconciliations#page3", as: 'page3'
  get 'reconciliations/page4' => "reconciliations#page4", as: 'page4'
  get 'reconciliations/page5' => "reconciliations#page5", as: 'page5'
  get 'reconciliations/page6' => "reconciliations#page6", as: 'page6'
  get 'reconciliations/page7' => "reconciliations#page7", as: 'page7'
  get 'reconciliations/page8' => "reconciliations#page8", as: 'page8'
  get 'reconciliations/page9' => "reconciliations#page9", as: 'page9'
  get 'reconciliations/page10' => "reconciliations#page10", as: 'page10'
  get 'reconciliations/page11' => "reconciliations#page11", as: 'page11'
  get 'reconciliations/page12' => "reconciliations#page12", as: 'page12'
  get 'reconciliations/page13' => "reconciliations#page13", as: 'page13'
  get 'reconciliations/page14' => "reconciliations#page14", as: 'page14'

  get 'users/:id/exit' => 'users#exit', as: 'user_exit'
  get 'users/:id/withdrawal' => 'users#withdrawal', as: 'withdrawal'

  resources :sharings, only: [:new, :create, :show, :edit, :update, :destroy]
  resources :meetings
  resources :notifications, only: [:index, :destroy]

  resources :messages, only: [:create]
  resources :rooms, only: [:create, :show]

  resources :posts do
    resource :favorites, only: [:create, :destroy]
    resources :post_comments, only: [:create, :destroy]
  end

  resources :tags do
    get 'posts', to: 'posts#search'
  end

  root to: 'homes#top'
  devise_for :users

  resources :users, only: [:show, :edit, :update] do
    resource :relationships, only: [:create, :destroy]
    get 'followings' => 'relationships#followings', as: 'followings'
    get 'followers' => 'relationships#followers', as: 'followers'
  end
  get 'homes/about'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  attachment :image
  has_many :post_comments, dependent: :destroy
  has_many :tag_maps, dependent: :destroy
  has_many :tags, through: :tag_maps
  has_many :favorites, dependent: :destroy

  has_many :notifications, dependent: :destroy

  def save_tag(sent_tags)
    current_tags = tags.pluck(:tag_name) unless tags.nil?
    old_tags = current_tags - sent_tags
    new_tags = sent_tags - current_tags

    old_tags.each do |old|
      post_tags.delete Tag.find_by(tag_name: old)
    end

    new_tags.each do |new|
      new_post_tag = Tag.find_or_create_by(tag_name: new)
      tags << new_post_tag
    end
  end

  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end

  def create_notification_favorite!(current_user)
    temp = Notification.where(["visitor_id = ? and visited_id = ? and post_id = ? and action = ? ", current_user.id, user_id, id, 'favorite'])
    if temp.blank?
      notification = current_user.active_notifications.new(
        post_id: id,
        visited_id: user_id,
        action: 'favorite'
      )
      if notification.visitor_id == notification.visited_id
        notification.checked = true
      end
      notification.save if notification.valid?
    end
  end

  def create_notification_post_comment!(current_user, post_comment_id)
    temp_ids = PostComment.select(:user_id).where(post_id: id).where.not(user_id: current_user.id).distinct
    temp_ids.each do |temp_id|
      save_notification_post_comment!(current_user, post_comment_id, temp_id['user_id'])
    end
    save_notification_post_comment!(current_user, post_comment_id, user_id) if temp_ids.blank?
  end

  def save_notification_post_comment!(current_user, post_comment_id, visited_id)
    notification = current_user.active_notifications.new(
      post_id: id,
      post_comment_id: post_comment_id,
      visited_id: visited_id,
      action: 'post_comment'
    )
    if notification.visitor_id == notification.visited_id
      notification.checked = true
    end
    notification.save if notification.valid?
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!, except: [:index]

  def new
    @post = current_user.posts.new
  end

  def create
    @post = current_user.posts.new(post_params)
    tag_list = params[:post][:tag_name].split(/[[:blank:]]+/).select(&:present?)
    if @post.save
      @post.save_tag(tag_list)
      redirect_to posts_path
    else
      redirect_back(fallback_location: root_path)
    end
  end

  def index
    @posts = Post.page(params[:page]).reverse_order
    @tag_list = Tag.all
  end

  def show
    @post = Post.find(params[:id])
    @post_comment = PostComment.new
    @post_comments = @post.post_comments
    @post_tags = @post.tags
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])
    @post.update(post_params)
    redirect_to post_path(@post)
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    redirect_to posts_path
  end

  def search
    @tag_list = Tag.all
    @tag = Tag.find(params[:tag_id])
    @posts = @tag.posts.all
  end

  private

  def post_params
    params.require(:post).permit(:name, :image, :content, :title)
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_list.html.erb
<% posts.each do |post| %>
  <div class="card mb-3 mx-auto" style="max-width: 800px;">
    <div class="row no-gutters">
      <div class="col-md-4">
        <%= link_to post_path(post.id) do %>
        <%= attachment_image_tag post,:image,width: "140",class: "card-img" %>
        <% end %>
      </div>
        <div class="col-md-8">
        <div class="card-body">
          <h5 class="card-title"><%= post.created_at.strftime('%Y/%m/%d') %></h5>
          <p class="card-text"><%= post.content %></p>
          <p class="card-text"><small class="text-muted">投稿者:<%= post.name %></small></p>
          <%= link_to "#{post.post_comments.count}コメント",post_path(post.id) %>
        </div>
      </div>
      </div>
    </div>
  </div>
<% end %>
<%= paginate posts %>

app/views/posts/_post.html.erb
<% if post.favorited_by?(current_user) %>
  <%= link_to post_favorites_path(post), method: :delete, remote: true do %>
    ❤️<%= post.favorites.count %> いいねをやめる
  <% end %>
<% else %>
  <%= link_to post_favorites_path(post), method: :post, remote: true do %>
    ♡<%= post.favorites.count %> いいねをする
  <% end %>
<% end %>

app/views/posts/edit.html.erb
<p class="lead-form mt-5">編集する</p>
<%= form_with model: @post, local:true do |f| %>

<div class="field">
  <p class="label">写真</p>
  <%= f.attachment_field :image, class: "inputs" %>
</div>

<div class="field">
  <p class="label">名前</p>
  <%= f.text_field :name, class: "inputs" %>
</div>

<div class="field">
  <p class="label">タイトル</p>
  <%= f.text_field :title, class: "inputs" %>
</div>

<div class="field">
  <p class="label">内容</p>
  <%= f.text_area :content, class: "inputs" %>
</div>

<%= f.submit "保存", class: "btn btn-primary px-5 mt-3" %>

<% end %>

app/views/posts/index.html.erb
<%= paginate @posts %>
<div class="news-contents wrapper">
	    <aside class="order-2 tag">
			<h3 class="sub-title">タグリスト</h3>
	 	    <ul class="sub-menu">
		 		<% @tag_list.each do |list| %>
		 			<li>
		 				<%= link_to list.tag_name, tag_posts_path(tag_id: list.id) %>
			    		<%= "(#{list.posts.count})" %>
			    	</li>
				<% end %>
		 	</ul>
		 	</aside>
		<!--ここから投稿一覧部分/もう少し改善の余地あり-->
		 	<article class="article order-1">
			 		<% @posts.each do |post| %>
					 		<hr>
							 	<header class="post-info text-nowrap">
							 		<h2 class="post-title"><%= post.title %></h2>
							 		<p class="post-date"><%= post.created_at.strftime("%m/%d")%><span><%= post.created_at.strftime("%Y")%></span></p>
							 		<% if user_signed_in? %>
							 			<p class="post-cat">投稿者：<%= post.name %><%= link_to "コメントを見る",post_path(post.id), class: "ml-4 text-primary mr-4" %><span id="favorites_buttons_<%= post.id %>"><%= render partial: 'posts/post', locals: { post: post} %></span></p>
							 		<% end %>
							 	</header>
							 	<%= link_to post_path(post.id) do %>
					        <%= attachment_image_tag post,:image, class: "img" %>
					      <% end %>
				      	<p class="mb-5 h5">内容：<%= post.content %></p>
				      </hr>
		      		<% end %>
		 	</article>
		<!--ここまでが投稿一覧分部分 	-->


	<!--ここからタグリスト-->
		 	<!--<aside>-->
			 <!--		<h3 class="sub-title">タグリスト</h3>-->
				<!-- 	<ul class="sub-menu">-->
				<!-- 		<% @tag_list.each do |list| %>-->
				<!-- 			<li>-->
				<!-- 				<%= link_to list.tag_name, tag_posts_path(tag_id: list.id) %>-->
				<!--    		<%= "(#{list.posts.count})" %>-->
				<!-- 			</li>-->
				<!-- 		<% end %>-->
				<!-- 	</ul>-->
		 	<!--</aside>-->
	<!--ここまでがタグリスト 	-->
</div>

app/views/posts/new.html.erb
<p class="lead-form mt-5">思い出を残す</p>
    <%= form_with model: @post, local:true do |f| %>

    <div class="field">
        <p class="label">写真</p>
        <%= f.attachment_field :image, class: "inputs" %>
    </div>

    <div class="field">
        <p class="label">名前</p>
        <%= f.text_field :name, class: "inputs" %>
    </div>

    <div class="field">
        <p class="label">タイトル</p>
        <%= f.text_field :title, class: "inputs" %>
    </div>

    <div class="field">
        <p class="label">内容</p>
        <%= f.text_area :content, class: "inputs" %>
    </div>

    <div class="field">
        <p class="label">タグ<br>
            <%= "例：音楽 文芸" %>
        </p>
        <%= f.text_area :tag_name,class: "inputs",placeholder: "スペースを入力することで複数のタグを付けることができます。" %>
    </div>
    <%= f.submit "記録する", class: "btn btn-primary px-5 mt-3" %>
    <% end %>

app/views/posts/search.html.erb
<aside class="tag">
 		<h3 class="sub-title">タグリスト</h3>
 		<ul class="sub-menu">
 			<% @tag_list.each do |list| %>
 			<li>
 				<%= link_to list.tag_name, tag_posts_path(tag_id: list.id) %>
    		<%= "(#{list.posts.count})" %>
 			</li>
 			<% end %>
 		</ul>
 </aside>

<br>
<h4 class="ml-4">タグが<strong><%= @tag.tag_name %></strong>の投稿一覧</h4>
<br>


<div class="wrapper grid text-center">
  <% @posts.each do |post| %>
    <div class="item">
      <%= link_to post_path(post.id) do %>
        <%= attachment_image_tag post,:image,width: "200", height: "200", class: "img"%>
      <% end %>
      <p><%= post.created_at.strftime('%Y/%m/%d') %></p>
    </div>
  <% end %>
</div>
<br>

app/views/posts/show.html.erb
<div class="contents">
  <div class="row">
    <div class="col-7">
      <h2 class="p-4">投稿詳細</h2>
        <div class="card mb-3 mt-5 ml-5" style="max-width: 600px;">
          <div class="row no-gutters">
            <div class="col-md-4">
              <%= link_to user_path(@post.user_id) do %>
                <%= attachment_image_tag @post,:image,width: "140",height: "200",class: "card-img" %>
              <% end %>
            </div>
            <div class="col-md-8">
              <div class="card-body">
                <h5 class="card-title"><%= @post.created_at.strftime('%Y/%m/%d')%><%= @post.title%></h5>
                <p class="card-text"><%= @post.content %></p>
                <% if @post.user_id == current_user.id %>
                  <%= link_to "編集する",edit_post_path(@post), class: "btn btn-success px-3 mt-1 mb-3 text-white" %>
                  <%= link_to "削除する", post_path(@post), method: :delete, class: "btn btn-danger px-3 mt-1 mb-3 text-white" %>
                <% end %>
                  <p>
                    <span id = "comments-count">コメント<%= @post.post_comments.count %>件</span>
                    <span id="favorites_buttons_<%= @post.id %>"><%= render partial: 'posts/post', locals: { post: @post} %></span>
                  </p>
              </div>
            </div>
          </div>
        </div>
     </div>
     <div class="col-5 new-comment ml-5 mt-5">
       <%= render partial: 'post_comments/form' , locals: { post: @post, post_comment: @post_comment} %>
     </div>
  </div>
</div>

<div class="comments pt-5">
  <h2>コメント一覧</h2>
  <table class="table">
    <thead>
      <tr>
        <th scope="col">名前</th>
        <th scope="col">日付</th>
        <th scope="col">コメント</th>
        <th scope="col"></th>
      </tr>
    </thead>
    <span id="comments_area"><%= render partial: 'post_comments/index', locals: { post_comments: @post_comments } %></span>
  </table>
</div>