config/routes.rb
Rails.application.routes.draw do
  get 'reconciliations/page1' => "reconciliations#page1", as: 'page1'
  get 'reconciliations/page2' => "reconciliations#page2", as: 'page2'
  get 'reconciliations/page3' => "reconciliations#page3", as: 'page3'
  get 'reconciliations/page4' => "reconciliations#page4", as: 'page4'
  get 'reconciliations/page5' => "reconciliations#page5", as: 'page5'
  get 'reconciliations/page6' => "reconciliations#page6", as: 'page6'
  get 'reconciliations/page7' => "reconciliations#page7", as: 'page7'
  get 'reconciliations/page8' => "reconciliations#page8", as: 'page8'
  get 'reconciliations/page9' => "reconciliations#page9", as: 'page9'
  get 'reconciliations/page10' => "reconciliations#page10", as: 'page10'
  get 'reconciliations/page11' => "reconciliations#page11", as: 'page11'
  get 'reconciliations/page12' => "reconciliations#page12", as: 'page12'
  get 'reconciliations/page13' => "reconciliations#page13", as: 'page13'
  get 'reconciliations/page14' => "reconciliations#page14", as: 'page14'

  get 'users/:id/exit' => 'users#exit', as: 'user_exit'
  get 'users/:id/withdrawal' => 'users#withdrawal', as: 'withdrawal'

  resources :sharings, only: [:new, :create, :show, :edit, :update, :destroy]
  resources :meetings
  resources :notifications, only: [:index, :destroy]

  resources :messages, only: [:create]
  resources :rooms, only: [:create, :show]

  resources :posts do
    resource :favorites, only: [:create, :destroy]
    resources :post_comments, only: [:create, :destroy]
  end

  resources :tags do
    get 'posts', to: 'posts#search'
  end

  root to: 'homes#top'
  devise_for :users

  resources :users, only: [:show, :edit, :update] do
    resource :relationships, only: [:create, :destroy]
    get 'followings' => 'relationships#followings', as: 'followings'
    get 'followers' => 'relationships#followers', as: 'followers'
  end
  get 'homes/about'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/anniversary.rb
class Anniversary < ApplicationRecord
  belongs_to :user
end

app/models/entry.rb
class Entry < ApplicationRecord
  belongs_to :user
  belongs_to :room
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

app/models/meeting.rb
class Meeting < ApplicationRecord

  belongs_to :user

  def self.search(search) # self.でクラスメソッドとしている
    if search # Controllerから渡されたパラメータが!= nilの場合は、titleカラムを部分一致検索
      Meeting.where(['name LIKE ?', "%#{search}%"])
    else
      Meeting.all # 全て表示。
    end
  end
end

app/models/message.rb
class Message < ApplicationRecord
  # validates :message, presence: true
  belongs_to :user
  belongs_to :room
end

app/models/notification.rb
class Notification < ApplicationRecord
  default_scope -> { order(created_at: :desc) }
  belongs_to :post, optional: true
  belongs_to :comment, optional: true

  belongs_to :visitor, class_name: 'User', foreign_key: 'visitor_id', optional: true
  belongs_to :visited, class_name: 'User', foreign_key: 'visited_id', optional: true
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  attachment :image
  has_many :post_comments, dependent: :destroy
  has_many :tag_maps, dependent: :destroy
  has_many :tags, through: :tag_maps
  has_many :favorites, dependent: :destroy

  has_many :notifications, dependent: :destroy

  def save_tag(sent_tags)
    current_tags = tags.pluck(:tag_name) unless tags.nil?
    old_tags = current_tags - sent_tags
    new_tags = sent_tags - current_tags

    old_tags.each do |old|
      post_tags.delete Tag.find_by(tag_name: old)
    end

    new_tags.each do |new|
      new_post_tag = Tag.find_or_create_by(tag_name: new)
      tags << new_post_tag
    end
  end

  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end

  def create_notification_favorite!(current_user)
    temp = Notification.where(["visitor_id = ? and visited_id = ? and post_id = ? and action = ? ", current_user.id, user_id, id, 'favorite'])
    if temp.blank?
      notification = current_user.active_notifications.new(
        post_id: id,
        visited_id: user_id,
        action: 'favorite'
      )
      if notification.visitor_id == notification.visited_id
        notification.checked = true
      end
      notification.save if notification.valid?
    end
  end

  def create_notification_post_comment!(current_user, post_comment_id)
    temp_ids = PostComment.select(:user_id).where(post_id: id).where.not(user_id: current_user.id).distinct
    temp_ids.each do |temp_id|
      save_notification_post_comment!(current_user, post_comment_id, temp_id['user_id'])
    end
    save_notification_post_comment!(current_user, post_comment_id, user_id) if temp_ids.blank?
  end

  def save_notification_post_comment!(current_user, post_comment_id, visited_id)
    notification = current_user.active_notifications.new(
      post_id: id,
      post_comment_id: post_comment_id,
      visited_id: visited_id,
      action: 'post_comment'
    )
    if notification.visitor_id == notification.visited_id
      notification.checked = true
    end
    notification.save if notification.valid?
  end
end

app/models/post_comment.rb
class PostComment < ApplicationRecord
  belongs_to :user
  belongs_to :post

  has_many :notifications, dependent: :destroy
end

app/models/reconciliation.rb
class Reconciliation < ApplicationRecord
  attachment :image
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"
end

app/models/room.rb
class Room < ApplicationRecord
  has_many :messages, dependent: :destroy
  has_many :entries, dependent: :destroy
end

app/models/sharing.rb
class Sharing < ApplicationRecord
  belongs_to :user
  attachment :profile_image
  validates :email, uniqueness: true
  self.inheritance_column = :_type_disabled
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :tag_maps, dependent: :destroy, foreign_key: 'tag_id'
  has_many :posts, through: :tag_maps
end

app/models/tag_map.rb
class TagMap < ApplicationRecord
  belongs_to :post
  belongs_to :tag
  validates :post_id, presence: true
  validates :tag_id, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable


  validates :login_name, uniqueness: true
  validates :email, uniqueness: true


  has_many :posts, dependent: :destroy
  has_many :post_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :sharings, dependent: :destroy
  attachment :profile_image

  has_many :reverse_of_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  has_many :followers, through: :reverse_of_relationships, source: :follower

  has_many :relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  has_many :followings, through: :relationships, source: :followed

  has_many :active_notifications, class_name: 'Notification', foreign_key: 'visitor_id', dependent: :destroy
  has_many :passive_notifications, class_name: 'Notification', foreign_key: 'visited_id', dependent: :destroy

  has_many :messages, dependent: :destroy
  has_many :entries, dependent: :destroy

  has_many :meetings, dependent: :destroy

  def active_for_authentication
    super && (is_valid == false)
  end

  def follow(user_id)
    relationships.create(followed_id: user_id)
  end

  def unfollow(user_id)
    relationships.find_by(followed_id: user_id).destroy
  end

  def following?(user)
    followings.include?(user)
  end

  def create_notification_follow!(current_user)
    temp = Notification.where(["visitor_id = ? and visited_id = ? and action = ? ", current_user.id, id, 'follow'])
    if temp.blank?
      notification = current_user.active_notifications.new(
        visited_id: id,
        action: 'follow'
      )
      notification.save if notification.valid?
    end
  end
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/meetings_helper.rb
module MeetingsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MemoryReminder</title>
    <!--レスポンシブデザイン-->
    <meta name="viewport" content="width=device-width,initial-scale=1.0">
    <!--タグ用コード-->
    <%= csrf_meta_tags %>
    <!--CSS用-->
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" type="text/css" href="//cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick.css"/>
    <link rel="stylesheet" type="text/css" href="//cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick-theme.css"/>
    <!--Javascript-->
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script type="text/javascript" src="//cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick.min.js"></script>
  </head>

  <body>
    <header>
      <!--もしログインしていたら-->
        <% if user_signed_in? %>
          <nav class="navbar navbar-light navbar-expand-md bg-light">
            <!--ロゴ用のHTML-->
            <%= link_to posts_path , class: "navbar-brand pl-5" do %>
              <%= image_tag 'logo.jpg', alt: "logo",style: 'height:30px;width:170px;' %>
            <% end %>
            <!--ロゴここまで-->
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#responsiveMenu" aria-controls="responsiveMenu" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="responsiveMenu">
              <ul class="navbar-nav ml-auto">
                <% if unchecked_notifications.any? %>
                  <i class="fa fa-circle" style="color: gold;"></i>
                <% end %>
                <li class="navbar-item pr-5"><%= link_to "通知",notifications_path,class: "nav-link" %></li>
                <li class="navbar-item pr-5"><%= link_to "マイページ",user_path(current_user.id),class: "nav-link" %></li>
                <li class="navbar-item pr-5"><%= link_to "みんなの思い出", posts_path,class: "nav-link" %></li>
                <li class="navbar-item pr-5"><%= link_to "思い出を残す",new_post_path,class: "nav-link" %></li>
                <li class="navbar-item pr-5"><%= link_to "記念日",meetings_path,class: "nav-link" %></li>
                <% if sharing %>
                  <li class="navbar-item pr-5"><%= link_to "仲直り",page1_path,class: "nav-link" %></li>
                <% end %>
                <li class="navbar-item pr-5"><%= link_to "ログアウト",destroy_user_session_path,method: :delete,class: "nav-link" %></li>
              </ul>
            </div>
          </nav>
      <!--ログインしてない時-->
        <% else %>
          <nav class="navbar navbar-light navbar-expand-md bg-light">
              <%= link_to root_path , class: "navbar-brand pl-5" do %>
                <%= image_tag 'logo.jpg', alt: "logo",style: 'height:30px;width:170px;' %>
              <% end %>
              <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#responsiveMenu" aria-controls="responsiveMenu" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
              </button>
              <div class="collapse navbar-collapse" id="responsiveMenu">
                <ul class="navbar-nav ml-auto">
                  <li class="navbar-item pr-5"><%= link_to "どんなサイト?", homes_about_path %></li>
                  <li class="navbar-item pr-5"><%= link_to "思い出一覧",posts_path %></li>
                  <li class="navbar-item pr-5"><%= link_to "新規登録",new_user_registration_path %></li>
                  <li class="navbar-item pr-5"><%= link_to "ログイン",new_user_session_path %></li>
                </ul>
              </div>
          </nav>
        <% end %>
    </header>
      <% if flash[:notice] %>
        <div class="alert alert-info text-center">
          <%= flash[:notice] %>
        </div>
      <% end %>
    <%= yield %>
    <footer class="mt-5">
      <div class="wrapper bg-light text-center" style="height: 70px;">
        <p class="pt-4"><small>&copy; 2021 Memory Reminder</small></p>
      </div>
    </footer>
  </body>
</html>